### ISSUE TITLE
Golonka/BBCode Doesn't exists

### ISSUE THREAD

**Issue by tetra7** [nenuadrian/Secret-Republic-Hacker-Game-ORPBG-Alpha#101]
https://github.com/golonka/BBCodeParser

Composer can not download golonka BBCodeParser.
Messaging missions etc. doesn't working. 

The Error: Class 'classes\Golonka\BBCode\BBCodeParser' not found

**Comment by nenuadrian** [comment]
Will fix, I refactored this code last minute as it wasn't using a dependency system at all

**Comment by nenuadrian** [comment]
Fixed
