### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by trizin** [nenuadrian/Secret-Republic-Hacker-Game-ORPBG-Alpha#102]
I'm trying to register and play the game from "https://alpha.secretrepublic.net/"

When i click "obtain citizenship" i get the following error:

"SQLSTATE[HY000]: General error: 1364 Field 'group' doesn't have a default value with query: "INSERT INTO `user` (`username`, `password`, `email`) VALUES ('asdavasasd', 'Sz1tHrN9YAvtFQchywGlKH2SlFrHdim8Jx1/LDkwG9E=', '"

**Comment by wumix** [comment]
Yes i habe the same problem

**Comment by nenuadrian** [comment]
Hey Trizin, this took a long time to answer but I have set up the codebase per instructions for a live preview which is linked in the Readme now and I have not encountered this issue

Please reopen if any problems
