### ISSUE TITLE
open world

### ISSUE THREAD

**Issue by AleWiccan** [nenuadrian/Secret-Republic-Hacker-Game-ORPBG-Alpha#103]
PHP 7.3
Fuel\Core\PhpErrorException [ Warning ]:
get_class() expects parameter 1 to be object, null given
D:/Servers/Server7.3/htdocs/SRH/fuel/core/classes/security.php @ line 241

236            foreach ($value as $k => $v)
237            {
238                $value[$k] = static::htmlentities($v, $flags, $encoding, $double_encode);
239            }
240        }
241        elseif ($value instanceof \Iterator or get_class($value) == 'stdClass')
242        {
243            // Add to $already_cleaned variable
244            $already_cleaned[] = $value;
245
246            foreach ($value as $k => $v)

Backtrace

    D:/Servers/Server7.3/htdocs/SRH/fuel/core/bootstrap.php @ line 103
    D:/Servers/Server7.3/htdocs/SRH/fuel/core/classes/security.php @ line 241
    D:/Servers/Server7.3/htdocs/SRH/fuel/core/classes/security.php @ line 156
    D:/Servers/Server7.3/htdocs/SRH/fuel/core/classes/security.php @ line 135
    D:/Servers/Server7.3/htdocs/SRH/fuel/core/classes/security.php @ line 135
    D:/Servers/Server7.3/htdocs/SRH/fuel/core/classes/view.php @ line 294
    D:/Servers/Server7.3/htdocs/SRH/fuel/core/classes/view.php @ line 305
    D:/Servers/Server7.3/htdocs/SRH/fuel/core/classes/view.php @ line 260
    D:/Servers/Server7.3/htdocs/SRH/fuel/core/classes/view.php @ line 665
    D:/Servers/Server7.3/htdocs/SRH/fuel/core/classes/view.php @ line 213
    D:/Servers/Server7.3/htdocs/SRH/fuel/core/classes/response.php @ line 382
    D:/Servers/Server7.3/htdocs/SRH/public_html/index.php @ line 113

**Comment by magic-space** [comment]
What is your PHP Version?

`Note: Explicitly passing NULL as the object is no longer allowed as of PHP 7.2.0. The parameter is still optional and calling get_class() without a parameter from inside a class will work, but passing NULL now emits an E_WARNING notice.`

Downgrading PHP is not usually the best or long term way to solve problems*; instead you need to wrap the get_class in a checker function such as is_object, or inversely, is_null.


Liebe Grüße 

Love greetings

**Comment by AleWiccan** [comment]
What is the required version of PHP? I thought it was 7.3

**Comment by AleWiccan** [comment]
Solved. Add an @ in front of the function to ignore the error and it works:
```
241 elseif ($value instanceof \Iterator or @get_class($value) == 'stdClass')
268 throw new \RuntimeException('Object class "'.@get_class($value).'" could not be converted to string or 
```

**Comment by magic-space** [comment]
Okay my bad.
Have you interested to develop the game?

please visit https://idlegames.ddnss.de

You find more games on my website.
Greetings

AleWiccan <notifications@github.com> schrieb am Sa., 15. Aug. 2020, 23:12:

**Comment by nenuadrian** [comment]
@AleWiccan  @magic-space 

This should be resolved now with a few commits pushed in today 

Let me know otherwise
